USE shopping;
SELECT * FROM customers limit 20;

DESCRIBE customers;


# Q1. what is the total revenue generated by male vs female customers ?
select Gender, SUM('Purchase_Amount_(USD)') as revenue from customers group by Gender;

#Q2. which customers used a discount but still spent more than the average purchase amount?

SELECT Customer_ID, `Purchase_Amount_(USD)`
FROM customers
WHERE discount_applied = 'Yes'
  AND `Purchase_Amount_(USD)` >= (
        SELECT AVG(`Purchase_Amount_(USD)`)
        FROM customers
      );
      
#Q3. which are the top 5 products with the highest average review rating?
SELECT item_purchased, round(avg(review_rating),2)as "Average Product Rating"
FROM customers
group by item_purchased
order by avg(review_rating) desc limit 5;


#Q4. Compare the average purchase amount between standard and express shipping.

SELECT Shipping_Type,
ROUND(AVG(`Purchase_Amount_(USD)`), 2) AS avg_purchase_amount
FROM customers
WHERE Shipping_Type IN ('Standard', 'Express')
GROUP BY Shipping_Type;

#Q5 Do subscribed customer spend more? Compare average spend and total revenue between subscriber and non-subscriber 

SELECT subscription_status,
COUNT(Customer_ID) AS total_customers,
ROUND(AVG(`Purchase_Amount_(USD)`), 2) AS avg_spend,
ROUND(SUM(`Purchase_Amount_(USD)`), 2) AS total_revenue
FROM customers
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;

#Q6. which 5 product have the highest percentage of purchases with discounts applied?


SELECT Item_Purchased,
ROUND(SUM(CASE WHEN Discount_Applied = 'yes' THEN 1 ELSE 0 END)/ COUNT(*) * 100, 2) AS discount_rate
FROM customers
GROUP BY Item_Purchased
ORDER BY discount_rate DESC
LIMIT 5;

#Q7. Segment customers into new, returning and loyal based on their total number of previous purchases 
# and show the count of each segmnet

WITH customer_type AS (
SELECT Customer_ID, previous_purchases,
CASE
	WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
    FROM customers
    )
    
    SELECT customer_segment, COUNT(*) AS "Number of customers"
    FROM customer_type
    GROUP BY customer_segment;
    
    
    
    #Q8. What are the top 3 most purchased products within each category?
    WITH item_counts AS (
    SELECT Category, Item_Purchased,
        COUNT(Customer_ID) AS total_orders,
        ROW_NUMBER() OVER ( PARTITION BY Category ORDER BY COUNT(Customer_ID) DESC
	) AS item_rank
    FROM customers
    GROUP BY Category, Item_Purchased
)
SELECT item_rank, Category, Item_Purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;


#Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT subscription_status,
COUNT(customer_ID) AS repeat_buyers
FROM customers 
WHERE previous_purchases > 5
GROUP BY subscription_status;


#10. what is the revenue contribution of age?
SELECT Age,
    SUM(`Purchase_Amount_(USD)`) AS total_revenue
FROM customers
GROUP BY Age
ORDER BY total_revenue DESC;



